export type FlowScenarioId = "all" | "success" | "auth" | "failure" | "utilities";

export type FlowNodeTone = "app" | "business" | "core" | "adapter" | "auth" | "support";

export type FlowEdgeTone = "main" | "success" | "auth" | "failure" | "utility" | "session";

export interface FlowScenario {
  id: FlowScenarioId;
  label: string;
  shortLabel: string;
  description: string;
  defaultNodeId: string;
}

export interface FlowNode {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
  module: string;
  title: string;
  summary: string;
  responsibility: string;
  input: string;
  output: string;
  watch: string;
  tone: FlowNodeTone;
  scenarios: Exclude<FlowScenarioId, "all">[];
}

export interface FlowEdge {
  id: string;
  path: string;
  tone: FlowEdgeTone;
  scenarios: Exclude<FlowScenarioId, "all">[];
  label?: string;
  labelX?: number;
  labelY?: number;
}

const everyScenario: Exclude<FlowScenarioId, "all">[] = ["success", "auth", "failure", "utilities"];

export const flowScenarios: FlowScenario[] = [
  {
    id: "all",
    label: "完整地图",
    shortLabel: "全流程",
    description:
      "同时显示正常返回、401 刷新、错误重试、取消与文件传输。先看模块位置，再按场景聚焦。",
    defaultNodeId: "client",
  },
  {
    id: "success",
    label: "正常 2xx",
    shortLabel: "2xx",
    description: "从页面调用业务函数，到拆掉响应信封，再把业务数据交回查询层。",
    defaultNodeId: "envelope",
  },
  {
    id: "auth",
    label: "401 刷新",
    shortLabel: "401",
    description: "并发请求共享一次刷新，保存新会话，重放原请求；刷新凭证失效时才结束会话。",
    defaultNodeId: "auth-engine",
  },
  {
    id: "failure",
    label: "失败与重试",
    shortLabel: "错误",
    description: "失败先归一化；只有安全读取和瞬时故障才进入退避重试，最终只通知一次。",
    defaultNodeId: "errors",
  },
  {
    id: "utilities",
    label: "取消与文件",
    shortLabel: "工具",
    description: "逻辑请求与物理尝试分别可取消；文件下载用 raw() 保留响应头并跳过信封解包。",
    defaultNodeId: "transfer",
  },
];

export const flowNodes: FlowNode[] = [
  {
    id: "view",
    x: 40,
    y: 45,
    width: 240,
    height: 72,
    module: "views/*.vue",
    title: "页面发起意图",
    summary: "展示数据或提交表单",
    responsibility: "只表达用户意图和界面反馈，不拼 URL，也不处理 token。",
    input: "用户操作、路由参数、表单数据",
    output: "调用 query / mutation",
    watch: "页面不应该直接 import Axios 或拼接后端地址。",
    tone: "app",
    scenarios: everyScenario,
  },
  {
    id: "query",
    x: 40,
    y: 145,
    width: 240,
    height: 72,
    module: "queries/*.ts · Pinia Colada",
    title: "管理服务端状态",
    summary: "缓存、loading、失效、去重",
    responsibility: "给页面提供查询和提交状态，并在写操作成功后让相关缓存失效。",
    input: "query key、mutation payload",
    output: "调用业务 API 函数并保存结果状态",
    watch: "它不保存 token，也不重复实现 HTTP 层的认证刷新。",
    tone: "app",
    scenarios: ["success", "auth", "failure"],
  },
  {
    id: "api-module",
    x: 40,
    y: 245,
    width: 240,
    height: 72,
    module: "api/modules/*.ts",
    title: "声明业务接口",
    summary: "方法、路径、请求体、返回类型",
    responsibility: "把 users、roles、auth 等领域动作翻译成 http.get / post / put / delete。",
    input: "领域参数，例如 userId、CreateUserPayload",
    output: "一个类型明确的 Promise<Result>",
    watch: "登录、退出等特殊接口在这里显式写 skipAuth，而不是让拦截器猜 URL。",
    tone: "business",
    scenarios: everyScenario,
  },
  {
    id: "facade",
    x: 340,
    y: 245,
    width: 240,
    height: 72,
    module: "api/http/index.ts",
    title: "唯一装配入口",
    summary: "创建 http，接入项目适配器",
    responsibility: "集中确定 baseURL、timeout、Cookie 策略，并只向应用导出 http 和会话入口。",
    input: "环境配置、AB3 Auth Adapter",
    output: "http、establishSession、endSession",
    watch: "这是组合根，不承载每次请求的执行逻辑。",
    tone: "core",
    scenarios: everyScenario,
  },
  {
    id: "client",
    x: 340,
    y: 345,
    width: 240,
    height: 72,
    module: "api/http/client.ts · execute()",
    title: "开启逻辑请求",
    summary: "校验配置、Loading、取消、上下文",
    responsibility:
      "把调用方眼里的一次请求包成完整生命周期；中间即使重试或重放，最后也只收尾一次。",
    input: "HttpRequestConfig 与 Result / Body 类型",
    output: "业务数据或统一 RequestError",
    watch: "逻辑请求不等于物理尝试，这是理解 Loading、取消和 attempts 的关键。",
    tone: "core",
    scenarios: everyScenario,
  },
  {
    id: "transfer",
    x: 40,
    y: 445,
    width: 240,
    height: 72,
    module: "api/http/transfer.ts",
    title: "文件传输工具",
    summary: "FormData、Blob、文件名、直链",
    responsibility: "上传继续走 http；Blob 下载用 raw() 保留响应头，直链下载只放行 HTTP(S)。",
    input: "File / Blob、下载地址、进度回调",
    output: "上传结果或 { blob, filename }",
    watch: "不要手写 multipart Content-Type；对象 URL 保存后必须释放。",
    tone: "support",
    scenarios: ["utilities"],
  },
  {
    id: "retry",
    x: 340,
    y: 445,
    width: 240,
    height: 72,
    module: "api/http/retry.ts · 可选",
    title: "包住一次 send()",
    summary: "仅安全读取 + 瞬时故障",
    responsibility:
      "只在显式开启时，对 GET / HEAD / OPTIONS 的网络、超时、502/503/504 做退避重试。",
    input: "一次物理发送函数、次数与总时间预算",
    output: "成功结果，或最后一次错误",
    watch: "写请求永不自动重试；接入查询库后通常只保留一层重试。",
    tone: "support",
    scenarios: ["failure"],
  },
  {
    id: "auth-request",
    x: 340,
    y: 545,
    width: 240,
    height: 72,
    module: "api/http/auth.ts · 请求拦截器",
    title: "准备认证信息",
    summary: "等待刷新、记录代际、注入 Bearer",
    responsibility:
      "跳过公开请求；有刷新在途就等待；给受管请求盖章并通过 Adapter 附上当前 access token。",
    input: "Axios config、内存会话、refreshPromise",
    output: "带 Authorization 和凭证代际的 config",
    watch: "Auth 是最后注册的请求拦截器，因此按 Axios 逆序规则最先执行。",
    tone: "auth",
    scenarios: everyScenario,
  },
  {
    id: "request-control",
    x: 340,
    y: 645,
    width: 240,
    height: 72,
    module: "api/http/request-control.ts",
    title: "登记物理尝试",
    summary: "attempts +1，组合取消信号",
    responsibility:
      "每次真正发出请求前创建物理 AbortController；响应回来后恢复原 signal 并清理监听器。",
    input: "原请求 signal、逻辑请求 signal",
    output: "可取消的一次物理请求",
    watch: "重试和 401 重放都会重新经过这里，所以 attempts 统计的是真实发送次数。",
    tone: "support",
    scenarios: everyScenario,
  },
  {
    id: "network",
    x: 340,
    y: 745,
    width: 240,
    height: 72,
    module: "Axios → Browser",
    title: "发送 HTTP 请求",
    summary: "baseURL、timeout、Cookie 策略生效",
    responsibility: "Axios 负责序列化并交给浏览器；浏览器按实例配置决定是否携带 HttpOnly Cookie。",
    input: "最终 Axios config",
    output: "HTTP 响应或 AxiosError",
    watch: "业务 URL 禁止绝对地址，防止调用方绕过可信 baseURL。",
    tone: "core",
    scenarios: everyScenario,
  },
  {
    id: "server",
    x: 340,
    y: 845,
    width: 240,
    height: 72,
    module: "Admin API",
    title: "后端处理请求",
    summary: "2xx 信封 / 4xx / 5xx",
    responsibility:
      "成功返回 { success: true, data }；失败用 HTTP 状态表达；刷新端点通过 Cookie 换新会话。",
    input: "业务请求或 /api/auth/refresh",
    output: "标准 HTTP 响应",
    watch: "HTTP 状态是成功失败的权威，业务信封不能把失败伪装成 2xx。",
    tone: "business",
    scenarios: everyScenario,
  },
  {
    id: "response-control",
    x: 640,
    y: 745,
    width: 240,
    height: 72,
    module: "request-control.ts · 响应拦截器",
    title: "先清理物理尝试",
    summary: "成功和失败都 finish()",
    responsibility: "移除本次物理控制器、解绑组合信号，并把 config.signal 恢复成调用方原值。",
    input: "AxiosResponse 或 AxiosError",
    output: "原样继续向后传递",
    watch: "401 重放会复用 config；不恢复 signal，新请求会拿到上一轮的废信号。",
    tone: "support",
    scenarios: everyScenario,
  },
  {
    id: "envelope",
    x: 640,
    y: 645,
    width: 240,
    height: 72,
    module: "adapters/envelope.ts",
    title: "校验并拆信封",
    summary: "2xx → response.data = data",
    responsibility:
      "正常业务响应必须满足 { success: true, data }；204 返回 undefined；raw() 明确跳过。",
    input: "成功的 AxiosResponse",
    output: "仍是 AxiosResponse，但 data 已是业务数据",
    watch: "失败响应不经过这个成功处理器，所以 401 会原样到达 Auth。",
    tone: "adapter",
    scenarios: ["success", "auth", "failure", "utilities"],
  },
  {
    id: "auth-response",
    x: 640,
    y: 545,
    width: 240,
    height: 72,
    module: "api/http/auth.ts · 响应拦截器",
    title: "判断是否接管 401",
    summary: "成功透传；受管 401 进入认证引擎",
    responsibility: "只处理本实例盖章、未 skipAuth 的 401；其他错误保持原样，正常响应直接通过。",
    input: "成功响应或 AxiosError",
    output: "响应、认证恢复结果或原错误",
    watch: "Auth 必须处在响应链最后，避免重放结果再次被信封适配器重复拆包。",
    tone: "auth",
    scenarios: ["success", "auth", "failure", "utilities"],
  },
  {
    id: "select",
    x: 640,
    y: 445,
    width: 240,
    height: 72,
    module: "client.ts · select + finally",
    title: "完成逻辑请求",
    summary: "取 data / raw response，统一收尾",
    responsibility:
      "request() 取业务 data，raw() 取完整响应；finally 只执行一次 Loading、信号和控制器清理。",
    input: "穿过全部响应拦截器的响应",
    output: "Result 或 AxiosResponse",
    watch: "重试与刷新重放都藏在内部，调用方仍只等待同一个 Promise。",
    tone: "core",
    scenarios: ["success", "auth", "utilities"],
  },
  {
    id: "return",
    x: 640,
    y: 345,
    width: 240,
    height: 72,
    module: "modules → queries → view",
    title: "交回业务结果",
    summary: "页面拿到的已经是领域数据",
    responsibility: "Promise 沿业务 API 和查询层返回；查询层更新缓存，页面只渲染结果。",
    input: "例如 AdminUserListItem[]",
    output: "界面状态与视图",
    watch: "正常页面无需知道 AxiosResponse、信封结构或 token 刷新。",
    tone: "app",
    scenarios: ["success", "auth", "utilities"],
  },
  {
    id: "auth-engine",
    x: 940,
    y: 545,
    width: 240,
    height: 72,
    module: "auth.ts · 401 状态机",
    title: "单飞刷新与最多重放一次",
    summary: "Promise、代际、熔断、失效去重",
    responsibility:
      "并发 401 共享 refreshPromise；旧代际直接用新凭证重放；失败按代际熔断，防止刷新风暴。",
    input: "401、requestVersion、sessionEpoch",
    output: "等待刷新、重放 config 或认证错误",
    watch: "重放后仍是 401 会结束会话，绝不再次刷新形成死循环。",
    tone: "auth",
    scenarios: ["auth"],
  },
  {
    id: "refresh-adapter",
    x: 940,
    y: 645,
    width: 240,
    height: 72,
    module: "adapters/auth.ts",
    title: "用独立实例刷新",
    summary: "Cookie → 完整新会话",
    responsibility:
      "裸 Axios 实例调用 refresh；校验返回结构后写入内存会话，避免刷新请求再次触发业务拦截器。",
    input: "HttpOnly refresh Cookie",
    output: "accessToken、过期时间、当前用户",
    watch: "刷新接口自己回答 401 才说明 refresh 会话已明确失效。",
    tone: "adapter",
    scenarios: ["auth"],
  },
  {
    id: "refresh-server",
    x: 940,
    y: 745,
    width: 240,
    height: 72,
    module: "POST /api/auth/refresh",
    title: "轮换刷新会话",
    summary: "成功 2xx；失效 401；抖动 5xx",
    responsibility: "后端验证 Cookie 并返回完整会话；轮换宽限负责跨标签页同时刷新的服务端正确性。",
    input: "浏览器自动携带的 Cookie",
    output: "新会话或明确 HTTP 错误",
    watch: "网络、超时、5xx 只代表暂时不可用，客户端保留当前会话并进入冷却。",
    tone: "business",
    scenarios: ["auth"],
  },
  {
    id: "session",
    x: 940,
    y: 845,
    width: 240,
    height: 72,
    module: "api/session.ts",
    title: "保存内存会话",
    summary: "Access Token 不落本地存储",
    responsibility: "保存 access token、两个过期时间和用户快照，并通知 Pinia store 与同步桥。",
    input: "登录或刷新得到的 AuthSessionResult",
    output: "新内存快照与订阅通知",
    watch: "旧版 localStorage 凭证会被清理；页面刷新后的恢复依靠 Cookie + profile 请求。",
    tone: "auth",
    scenarios: ["auth"],
  },
  {
    id: "session-bridge",
    x: 940,
    y: 945,
    width: 240,
    height: 72,
    module: "session-bridge.ts + session-sync.ts",
    title: "同步其他标签页",
    summary: "状态迁移 → BroadcastChannel",
    responsibility: "会话更新或终结时广播；远端采纳时抑制回声，并 resetAuthState 开启新代际。",
    input: "session-updated / session-ended",
    output: "其他标签页采用相同会话状态",
    watch: "事件屏障丢弃旧事件和重复事件，避免已退出的会话被迟到消息复活。",
    tone: "support",
    scenarios: ["auth"],
  },
  {
    id: "other-tab",
    x: 940,
    y: 1045,
    width: 240,
    height: 72,
    module: "Pinia auth store · 其他标签页",
    title: "界面与认证代际联动",
    summary: "登录、刷新、退出保持一致",
    responsibility: "Pinia 订阅内存会话更新界面；其他标签页采纳广播并让旧的在途刷新失效。",
    input: "本地订阅通知或跨标签页事件",
    output: "一致的登录界面与后续请求凭证",
    watch: "BroadcastChannel 负责同步结果，不负责跨标签页刷新互斥。",
    tone: "app",
    scenarios: ["auth"],
  },
  {
    id: "errors",
    x: 640,
    y: 845,
    width: 240,
    height: 72,
    module: "api/http/errors.ts",
    title: "归一化最终错误",
    summary: "http / network / timeout / cancel / config",
    responsibility: "把各种异常收敛成稳定错误类型，并补充安全路径、次数、耗时和错误来源。",
    input: "AxiosError、协议错误或未知异常",
    output: "HttpError / ApiEnvelopeFormatError",
    watch: "响应体和服务端原文默认不参与序列化，避免监控上报泄露敏感信息。",
    tone: "core",
    scenarios: ["auth", "failure", "utilities"],
  },
  {
    id: "presenter",
    x: 640,
    y: 945,
    width: 240,
    height: 72,
    module: "client.ts + error-presenter.ts",
    title: "展示与上报分流",
    summary: "cancel 静默；silent 仍上报",
    responsibility:
      "Presenter 把错误分类翻译成用户文案；client 决定 onError 与 onReport 是否触发。",
    input: "带上下文的 RequestError",
    output: "Toast、监控记录、向调用方抛错",
    watch: "认证已处理的错误只上报不重复提示；回调自身故障不会覆盖原始请求错误。",
    tone: "adapter",
    scenarios: ["auth", "failure", "utilities"],
  },
];

export const flowEdges: FlowEdge[] = [
  {
    id: "view-query",
    path: "M160 117 V145",
    tone: "main",
    scenarios: ["success", "auth", "failure"],
  },
  {
    id: "query-api",
    path: "M160 217 V245",
    tone: "main",
    scenarios: ["success", "auth", "failure"],
  },
  {
    id: "view-api-utility",
    path: "M90 117 V226 H120 V245",
    tone: "utility",
    scenarios: ["utilities"],
  },
  { id: "api-facade", path: "M280 281 H340", tone: "main", scenarios: everyScenario },
  { id: "facade-client", path: "M460 317 V345", tone: "main", scenarios: everyScenario },
  {
    id: "client-auth",
    path: "M460 417 V545",
    tone: "main",
    scenarios: ["success", "auth", "utilities"],
  },
  {
    id: "client-retry",
    path: "M460 417 V445",
    tone: "failure",
    scenarios: ["failure"],
    label: "显式开启",
    labelX: 472,
    labelY: 436,
  },
  { id: "retry-auth", path: "M460 517 V545", tone: "failure", scenarios: ["failure"] },
  { id: "auth-control", path: "M460 617 V645", tone: "main", scenarios: everyScenario },
  { id: "control-network", path: "M460 717 V745", tone: "main", scenarios: everyScenario },
  { id: "network-server", path: "M460 817 V845", tone: "main", scenarios: everyScenario },
  {
    id: "server-response-control",
    path: "M580 881 H610 V781 H640",
    tone: "success",
    scenarios: ["success", "auth", "failure", "utilities"],
    label: "响应先清理",
    labelX: 592,
    labelY: 835,
  },
  {
    id: "response-envelope",
    path: "M760 745 V717",
    tone: "success",
    scenarios: ["success", "utilities"],
  },
  {
    id: "envelope-auth-response",
    path: "M760 645 V617",
    tone: "success",
    scenarios: ["success", "utilities"],
  },
  {
    id: "auth-response-select",
    path: "M760 545 V517",
    tone: "success",
    scenarios: ["success", "auth", "utilities"],
  },
  {
    id: "select-return",
    path: "M760 445 V417",
    tone: "success",
    scenarios: ["success", "auth", "utilities"],
  },
  {
    id: "return-query",
    path: "M640 381 H610 V181 H280",
    tone: "success",
    scenarios: ["success", "auth"],
    label: "Result",
    labelX: 594,
    labelY: 281,
  },
  {
    id: "response-bypass-envelope",
    path: "M880 781 H905 V581 H880",
    tone: "auth",
    scenarios: ["auth", "failure"],
    label: "拒绝分支跳过 Envelope",
    labelX: 900,
    labelY: 690,
  },
  { id: "auth-response-engine", path: "M880 571 H940", tone: "auth", scenarios: ["auth"] },
  { id: "engine-refresh", path: "M1060 617 V645", tone: "auth", scenarios: ["auth"] },
  { id: "refresh-server", path: "M1060 717 V745", tone: "auth", scenarios: ["auth"] },
  { id: "refresh-session", path: "M1060 817 V845", tone: "session", scenarios: ["auth"] },
  {
    id: "session-engine",
    path: "M1180 881 H1210 V581 H1180",
    tone: "session",
    scenarios: ["auth"],
    label: "保存成功，代际 +1",
    labelX: 1096,
    labelY: 835,
  },
  {
    id: "engine-replay",
    path: "M940 591 H580",
    tone: "auth",
    scenarios: ["auth"],
    label: "原 config 最多重放一次",
    labelX: 710,
    labelY: 584,
  },
  { id: "session-bridge", path: "M1060 917 V945", tone: "session", scenarios: ["auth"] },
  { id: "bridge-other", path: "M1060 1017 V1045", tone: "session", scenarios: ["auth"] },
  {
    id: "other-reset",
    path: "M1180 1081 H1230 V561 H1180",
    tone: "session",
    scenarios: ["auth"],
    label: "远端采纳 + resetAuthState",
    labelX: 1080,
    labelY: 1037,
  },
  {
    id: "auth-error",
    path: "M880 601 H915 V881 H880",
    tone: "failure",
    scenarios: ["auth", "failure"],
    label: "非 401 / 刷新失败 / 二次 401",
    labelX: 900,
    labelY: 829,
  },
  {
    id: "network-error",
    path: "M580 781 H610 V881 H640",
    tone: "failure",
    scenarios: ["failure", "utilities"],
    label: "网络 / 超时 / 取消",
    labelX: 602,
    labelY: 840,
  },
  {
    id: "envelope-error",
    path: "M640 681 H620 V861 H700 V845",
    tone: "failure",
    scenarios: ["failure"],
    label: "协议格式错误",
    labelX: 624,
    labelY: 773,
  },
  {
    id: "errors-presenter",
    path: "M760 917 V945",
    tone: "failure",
    scenarios: ["auth", "failure", "utilities"],
  },
  {
    id: "errors-retry",
    path: "M640 881 H610 V481 H580",
    tone: "failure",
    scenarios: ["failure"],
    label: "符合条件且预算足够",
    labelX: 598,
    labelY: 661,
  },
  {
    id: "presenter-query",
    path: "M640 981 H305 V181 H280",
    tone: "failure",
    scenarios: ["auth", "failure"],
    label: "最终抛给调用方",
    labelX: 318,
    labelY: 968,
  },
  { id: "api-transfer", path: "M160 317 V445", tone: "utility", scenarios: ["utilities"] },
  {
    id: "transfer-client",
    path: "M280 481 H315 V381 H340",
    tone: "utility",
    scenarios: ["utilities"],
  },
  {
    id: "raw-transfer",
    path: "M640 801 H305 V481 H280",
    tone: "utility",
    scenarios: ["utilities"],
    label: "raw() 保留响应头",
    labelX: 318,
    labelY: 793,
  },
];
